-- Insert the complete AI marketplace products
INSERT INTO public.products (
  title, 
  description, 
  short_description, 
  category, 
  price, 
  downloads_count, 
  is_featured, 
  is_active, 
  tags, 
  product_code,
  implementation_guide,
  preview_content
) VALUES 
(
  'Complete AI Developer Bundle',
  'Everything you need: Universal Rules + Framework Specific + Enterprise Quality. This comprehensive bundle includes all our premium AI development rules, configurations, and templates. Perfect for professional developers who want the complete toolkit for AI-assisted development across all platforms and frameworks.',
  'Everything you need: Universal Rules + Framework Specific + Enterprise Quality',
  'Universal',
  9999,
  847,
  true,
  true,
  ARRAY['bundle', 'universal', 'react', 'enterprise', 'complete'],
  'ai_rules_0001',
  '1. Download the complete bundle package. 2. Extract all configuration files to your project. 3. Follow the included setup guide for your specific IDE. 4. Customize settings based on your project requirements. 5. Start coding with enhanced AI assistance.',
  'Complete bundle with 15+ configuration files for all major AI coding assistants'
),
(
  'AI Startup Accelerator Pack',
  'Essential AI rules for rapid MVP development and scaling. Designed specifically for startups who need to move fast and build efficiently. Includes optimized configurations for rapid prototyping, MVP development, and scaling patterns.',
  'Essential AI rules for rapid MVP development and scaling',
  'Universal',
  4999,
  623,
  true,
  true,
  ARRAY['startup', 'mvp', 'react', 'scaling', 'rapid-development'],
  'ai_rules_0002',
  '1. Download the startup accelerator package. 2. Choose your framework configuration. 3. Install the AI rules in your development environment. 4. Configure for rapid prototyping mode. 5. Start building your MVP with AI assistance.',
  'Optimized for startup velocity with lean development patterns'
),
(
  'Cursor AI Pro Rules - TDD & Clean Code',
  'Professional .cursorrules template with TDD enforcement - BEST SELLER. This is our most popular Cursor AI configuration, focusing on Test-Driven Development and clean code practices. Used by thousands of professional developers worldwide.',
  'Professional .cursorrules template with TDD enforcement - BEST SELLER',
  'Cursor AI',
  2999,
  1247,
  true,
  true,
  ARRAY['cursor', 'tdd', 'clean-code', 'testing', 'best-practices'],
  'ai_rules_0003',
  '1. Download the .cursorrules file. 2. Place it in your project root directory. 3. Restart Cursor IDE. 4. Configure TDD preferences in settings. 5. Start coding with enhanced TDD workflow.',
  'Professional-grade .cursorrules with TDD enforcement and clean code patterns'
),
(
  'AI Coding Assistant Universal Rules',
  'Universal AI rules compatible with all major coding assistants - MOST POPULAR. Works seamlessly with Cursor, GitHub Copilot, Codeium, and other AI coding tools. Our most versatile and widely-used configuration.',
  'Universal AI rules compatible with all major coding assistants - MOST POPULAR',
  'Universal',
  3999,
  2156,
  true,
  true,
  ARRAY['universal', 'clean-code', 'security', 'compatibility', 'popular'],
  'ai_rules_0004',
  '1. Download the universal configuration package. 2. Select your AI coding assistant. 3. Install the appropriate configuration file. 4. Customize security and code quality settings. 5. Enjoy enhanced AI assistance.',
  'Compatible with all major AI coding assistants with unified configuration'
),
(
  'Enterprise AI Code Review Rules',
  'Enterprise-grade AI rules for code review and quality assurance - Fortune 500 trusted. Used by major corporations for maintaining code quality standards and ensuring enterprise-level security and compliance.',
  'Enterprise-grade AI rules for code review and quality assurance - Fortune 500 trusted',
  'Enterprise',
  4999,
  432,
  true,
  true,
  ARRAY['enterprise', 'code-review', 'quality-assurance', 'security', 'compliance'],
  'ai_rules_0005',
  '1. Download the enterprise package. 2. Configure for your organization policies. 3. Set up code review automation. 4. Train team on enterprise standards. 5. Deploy across development teams.',
  'Enterprise-grade rules with Fortune 500 compliance and security standards'
),
(
  'Windsurf AI Cascade Rules',
  'Advanced cascade rules specifically designed for Windsurf AI development environment. Optimizes the cascade workflow and enhances AI-assisted development patterns unique to Windsurf.',
  'Advanced cascade rules for Windsurf AI development workflow',
  'Windsurf AI',
  2499,
  189,
  false,
  true,
  ARRAY['windsurf', 'cascade', 'workflow', 'optimization'],
  'ai_rules_0006',
  '1. Download Windsurf cascade configuration. 2. Import into Windsurf AI. 3. Configure cascade preferences. 4. Test workflow optimization. 5. Start enhanced development.',
  'Specialized cascade rules for Windsurf AI development environment'
),
(
  'Lovable.dev Agent Instructions',
  'Specialized agent instructions optimized for Lovable.dev platform. Enhances AI understanding of Lovable-specific patterns, component structures, and development workflows.',
  'Specialized agent instructions for Lovable.dev platform optimization',
  'lovable',
  1999,
  156,
  false,
  true,
  ARRAY['lovable', 'agent-instructions', 'platform-specific', 'optimization'],
  'ai_rules_0007',
  '1. Download Lovable agent instructions. 2. Configure in your Lovable project. 3. Set up platform-specific preferences. 4. Test AI understanding. 5. Start optimized development.',
  'Agent instructions tailored for Lovable.dev platform and workflows'
),
(
  'Claude AI Development Instructions',
  'Comprehensive instructions for Claude AI in development scenarios. Optimizes Claude for code generation, review, and technical documentation with development-specific prompts.',
  'Comprehensive development instructions for Claude AI optimization',
  'Claude AI',
  2199,
  298,
  false,
  true,
  ARRAY['claude', 'instructions', 'development', 'documentation'],
  'ai_rules_0008',
  '1. Download Claude instructions package. 2. Configure Claude with development prompts. 3. Set up code generation preferences. 4. Test documentation generation. 5. Start enhanced development.',
  'Development-focused instructions for Claude AI code generation and review'
),
(
  'V0 Vercel Development Templates',
  'Professional templates and configurations for V0 by Vercel. Includes optimized component generation patterns and deployment configurations for V0 development workflow.',
  'Professional templates and configurations for V0 by Vercel development',
  'V0 Vercel',
  1799,
  234,
  false,
  true,
  ARRAY['v0', 'vercel', 'templates', 'components', 'deployment'],
  'ai_rules_0009',
  '1. Download V0 templates package. 2. Import into V0 project. 3. Configure component patterns. 4. Set up deployment preferences. 5. Start template-based development.',
  'Optimized templates and patterns for V0 by Vercel development'
),
(
  'Framework-Specific React Blueprint',
  'Specialized React development blueprint with advanced patterns, hooks optimization, and React-specific AI assistance configurations for modern React development.',
  'Advanced React development blueprint with modern patterns and optimizations',
  'Framework Specific',
  2799,
  567,
  false,
  true,
  ARRAY['react', 'framework', 'hooks', 'patterns', 'modern'],
  'ai_rules_0010',
  '1. Download React blueprint. 2. Configure for React project. 3. Set up hooks and patterns. 4. Configure AI for React specifics. 5. Start optimized React development.',
  'React-specific blueprint with modern patterns and hooks optimization'
),
(
  'Debug Recipe Collection',
  'Comprehensive debugging recipes and AI-assisted troubleshooting patterns. Includes common bug patterns, debugging workflows, and AI prompts for efficient problem-solving.',
  'Comprehensive debugging recipes and AI-assisted troubleshooting patterns',
  'Debugging',
  1499,
  445,
  false,
  true,
  ARRAY['debugging', 'troubleshooting', 'recipes', 'problem-solving'],
  'ai_rules_0011',
  '1. Download debug recipes. 2. Configure debugging environment. 3. Set up troubleshooting patterns. 4. Configure AI for debugging. 5. Start efficient debugging.',
  'Debug recipes and patterns for AI-assisted troubleshooting'
),
(
  'Enterprise Security Kit',
  'Enterprise-grade security configurations and AI rules for secure code generation. Includes security patterns, vulnerability prevention, and compliance configurations.',
  'Enterprise security configurations for secure AI-assisted development',
  'Enterprise',
  5999,
  298,
  true,
  true,
  ARRAY['enterprise', 'security', 'compliance', 'vulnerability-prevention'],
  'ai_rules_0012',
  '1. Download security kit. 2. Configure security policies. 3. Set up vulnerability scanning. 4. Configure compliance rules. 5. Start secure development.',
  'Enterprise security configurations with compliance and vulnerability prevention'
);